/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as NouveauMotDePasseRouteImport } from './routes/nouveau-mot-de-passe'
import { Route as SolidariteRouteImport } from './routes/solidarite'
import { Route as TimelineRouteImport } from './routes/timeline'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedCarteRouteImport } from './routes/_authenticated/carte'
import { Route as AuthenticatedMesKmRouteImport } from './routes/_authenticated/mes-km'
import { Route as AuthenticatedProfilRouteImport } from './routes/_authenticated/profil'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const NouveauMotDePasseRoute = NouveauMotDePasseRouteImport.update({
  id: '/nouveau-mot-de-passe',
  path: '/nouveau-mot-de-passe',
  getParentRoute: () => rootRouteImport,
} as any)
const SolidariteRoute = SolidariteRouteImport.update({
  id: '/solidarite',
  path: '/solidarite',
  getParentRoute: () => rootRouteImport,
} as any)
const TimelineRoute = TimelineRouteImport.update({
  id: '/timeline',
  path: '/timeline',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCarteRoute = AuthenticatedCarteRouteImport.update({
  id: '/carte',
  path: '/carte',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMesKmRoute = AuthenticatedMesKmRouteImport.update({
  id: '/mes-km',
  path: '/mes-km',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProfilRoute = AuthenticatedProfilRouteImport.update({
  id: '/profil',
  path: '/profil',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/nouveau-mot-de-passe': typeof NouveauMotDePasseRoute
  '/solidarite': typeof SolidariteRoute
  '/timeline': typeof TimelineRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/carte': typeof AuthenticatedCarteRoute
  '/mes-km': typeof AuthenticatedMesKmRoute
  '/profil': typeof AuthenticatedProfilRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/nouveau-mot-de-passe': typeof NouveauMotDePasseRoute
  '/solidarite': typeof SolidariteRoute
  '/timeline': typeof TimelineRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/carte': typeof AuthenticatedCarteRoute
  '/mes-km': typeof AuthenticatedMesKmRoute
  '/profil': typeof AuthenticatedProfilRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/nouveau-mot-de-passe': typeof NouveauMotDePasseRoute
  '/solidarite': typeof SolidariteRoute
  '/timeline': typeof TimelineRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/_authenticated/carte': typeof AuthenticatedCarteRoute
  '/_authenticated/mes-km': typeof AuthenticatedMesKmRoute
  '/_authenticated/profil': typeof AuthenticatedProfilRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/nouveau-mot-de-passe'
    | '/solidarite'
    | '/timeline'
    | '/admin'
    | '/carte'
    | '/mes-km'
    | '/profil'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/nouveau-mot-de-passe'
    | '/solidarite'
    | '/timeline'
    | '/admin'
    | '/carte'
    | '/mes-km'
    | '/profil'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/nouveau-mot-de-passe'
    | '/solidarite'
    | '/timeline'
    | '/_authenticated/admin'
    | '/_authenticated/carte'
    | '/_authenticated/mes-km'
    | '/_authenticated/profil'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  NouveauMotDePasseRoute: typeof NouveauMotDePasseRoute
  SolidariteRoute: typeof SolidariteRoute
  TimelineRoute: typeof TimelineRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nouveau-mot-de-passe': {
      id: '/nouveau-mot-de-passe'
      path: '/nouveau-mot-de-passe'
      fullPath: '/nouveau-mot-de-passe'
      preLoaderRoute: typeof NouveauMotDePasseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/solidarite': {
      id: '/solidarite'
      path: '/solidarite'
      fullPath: '/solidarite'
      preLoaderRoute: typeof SolidariteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/timeline': {
      id: '/timeline'
      path: '/timeline'
      fullPath: '/timeline'
      preLoaderRoute: typeof TimelineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/carte': {
      id: '/_authenticated/carte'
      path: '/carte'
      fullPath: '/carte'
      preLoaderRoute: typeof AuthenticatedCarteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/mes-km': {
      id: '/_authenticated/mes-km'
      path: '/mes-km'
      fullPath: '/mes-km'
      preLoaderRoute: typeof AuthenticatedMesKmRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/profil': {
      id: '/_authenticated/profil'
      path: '/profil'
      fullPath: '/profil'
      preLoaderRoute: typeof AuthenticatedProfilRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
  AuthenticatedCarteRoute: typeof AuthenticatedCarteRoute
  AuthenticatedMesKmRoute: typeof AuthenticatedMesKmRoute
  AuthenticatedProfilRoute: typeof AuthenticatedProfilRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
  AuthenticatedCarteRoute: AuthenticatedCarteRoute,
  AuthenticatedMesKmRoute: AuthenticatedMesKmRoute,
  AuthenticatedProfilRoute: AuthenticatedProfilRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  NouveauMotDePasseRoute: NouveauMotDePasseRoute,
  SolidariteRoute: SolidariteRoute,
  TimelineRoute: TimelineRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
